### ISSUE TITLE
Rebase commit from master to development

### ISSUE THREAD

**Issue by arctair** [NDSU-CS313-Team7/GameProject#12]
@gage-askegard 0e1ed53d24f20283e09832412e2556159a5b721e looks like your commit went to master instead of development (and perhaps put all previous development commits into master,) so I'm going to try to move it over via git.

**Comment by GageAskegard** [comment]
Yeah I committed a bit hastily thinking I was in development. Thanks!

**Comment by GageAskegard** [comment]
If you can't, don't worry about it too much I didn't get a whole lot done

**Comment by arctair** [comment]
Was it just adding the tag to TagManager or did you make changes in the scene also?

**Comment by GageAskegard** [comment]
I also made changes to the scene. I added a "bunker" and a script as well. I believe I have a copy of the script though

**Comment by GageAskegard** [comment]
It appears to have worked. I'll close this now. Thanks a bunch!
