### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by GageAskegard** [NDSU-CS313-Team7/GameProject#3]
@arctair are there certain permissions set for the repository? I'm just messing around trying to get a feel for git so I created a new branch but I am unable to push it to the repository. I get an access denied error. This could just be my lack of knowledge here but it seemed like I did everything right up until this point. Any advice would be appreciated.

**Comment by arctair** [comment]
@GageAskegard permissions have now been reconfigured. Verify for me that you are able to make changes to the GameProject repository. Sorry for the confusion.

**Comment by GageAskegard** [comment]
It worked thanks!
